ALTER TABLE "schools"
  ADD COLUMN IF NOT EXISTS "zip_code"     VARCHAR(9),
  ADD COLUMN IF NOT EXISTS "street"       VARCHAR(200),
  ADD COLUMN IF NOT EXISTS "number"       VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "complement"   VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "neighborhood" VARCHAR(100);
